### ISSUE TITLE
Bad command configuration reference (V)...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#10]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch7-05-if-else-vars2.rsc#L4

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch7-05-if-else-vars2.rsc#L4

should be

    :local CurrentTime [/system clock get time];

in both cases.

**Comment by wifinigel** [comment]
Fixed in code repo & manuscripts. Thanks @tabad
