### ISSUE TITLE
Bad command configuration reference (VII)...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#12]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch7-07-nested-if-statements.rsc#L4

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch7-07-nested-if-statements.rsc#L4
should be

    :local CurrentTime [/system clock get time];

in both cases.

**Comment by wifinigel** [comment]
Fixed in code repo & book examples Thanks @tabad
