### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#14]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch8-06-while-infinite.rsc#L16

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch8-06-while-infinite.rsc#L16

should be

    :delay 1;

in both cases.

**Comment by wifinigel** [comment]
Fixed in code repo and in book manuscripts. Thanks @tabad
