### ISSUE TITLE
Bad configuration command reference...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#6]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch6-12-global-vars3.rsc#L28

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch6-12-global-vars3.rsc#L28

should be

    if ([/interface ethernet get $InterfaceId]->"running") do={

and

    if ([/interface/ethernet get $InterfaceId]->"running") do={

respectively.

**Comment by wifinigel** [comment]
Fixed in repo. Thanks @tabad
