### ISSUE TITLE
Bad configuration command reference (II)...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#7]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch7-01-basic-if.rsc#L7

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch7-01-basic-if.rsc#L7

should be

    :local CurrentTime [/system clock get time];

in both cases.

**Comment by wifinigel** [comment]
Code fixed in repo. Thanks @tabad!
