### ISSUE TITLE
Bad configuration command reference (III)...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#8]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch7-03-if-else.rsc#L7

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch7-03-if-else.rsc#L7

should be

    :local CurrentTime [/system clock get time];

in both cases.

**Comment by wifinigel** [comment]
Code sample in repo fixed & manuscripts updated. Thanks @tabad
