### ISSUE TITLE
Bad configuration command reference (IV)...

### ISSUE THREAD

**Issue by tabad** [wifinigel/MikrotikScripting#9]
The following lines:

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v6/ch7-04-if-else-vars.rsc#L4

and

https://github.com/wifinigel/MikrotikScripting/blob/b297ff4bbb7a1a1bcd622b6697eb5c14547e959e/scripts/v7/ch7-04-if-else-vars.rsc#L4

should be

    :local CurrentTime [/system clock get time];

in both cases.

**Comment by wifinigel** [comment]
Code repo fixed & manuscripts updated. Thanks @tabad.
